development:
  adapter: postgresql
  encoding: unicode
  database: blog-rails
  pool: 5
  host: localhost
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: blog-rails
  pool: 5
  username: postgres
  password: root

staging:
  url: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  url: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 